<?php
use App\Controllers\AuthController;
use App\Controllers\EspecieController;
return [
    'home' => ['GET', App\Controllers\HomeController::class, 'index', true],
    'login' => ['GET', AuthController::class, 'form', false],
    'login.submit' => ['POST', AuthController::class, 'login', false],
    'logout' => ['POST', AuthController::class, 'logout', true],
    'especies' => ['GET', EspecieController::class, 'index', true],
    'especies.create' => ['GET', EspecieController::class, 'create', true],
    'especies.store' => ['POST', EspecieController::class, 'store', true],
    'especies.edit' => ['GET', EspecieController::class, 'edit', true],
    'especies.update' => ['POST', EspecieController::class, 'update', true],
    'especies.destroy' => ['POST', EspecieController::class, 'destroy', true],
    'propietarios' => ['GET', App\Controllers\PropietarioController::class, 'index', true],
    'propietarios.create' => ['GET', App\Controllers\PropietarioController::class, 'create', true],
    'propietarios.store' => ['POST', App\Controllers\PropietarioController::class, 'store', true],
    'propietarios.edit' => ['GET', App\Controllers\PropietarioController::class, 'edit', true],
    'propietarios.update' => ['POST', App\Controllers\PropietarioController::class, 'update', true],
    'propietarios.destroy' => ['POST', App\Controllers\PropietarioController::class, 'destroy', true],
    'propietarios.show' => ['GET', App\Controllers\PropietarioController::class, 'show', true],
    'mascotas' => ['GET', App\Controllers\MascotaController::class, 'index', true],
    'mascotas.create' => ['GET', App\Controllers\MascotaController::class, 'create', true],
    'mascotas.store' => ['POST', App\Controllers\MascotaController::class, 'store', true],
    'mascotas.edit' => ['GET', App\Controllers\MascotaController::class, 'edit', true],
    'mascotas.update' => ['POST', App\Controllers\MascotaController::class, 'update', true],
    'mascotas.destroy' => ['POST', App\Controllers\MascotaController::class, 'destroy', true],
    'mascotas.show' => ['GET', App\Controllers\MascotaController::class, 'show', true],
    'cuotas' => ['GET', App\Controllers\CuotaController::class, 'index', true],
    'cuotas.create' => ['GET', App\Controllers\CuotaController::class, 'create', true],
    'cuotas.store' => ['POST', App\Controllers\CuotaController::class, 'store', true],
    'cuotas.edit' => ['GET', App\Controllers\CuotaController::class, 'edit', true],
    'cuotas.update' => ['POST', App\Controllers\CuotaController::class, 'update', true],
    'cuotas.destroy' => ['POST', App\Controllers\CuotaController::class, 'destroy', true],
    'cuotas.show' => ['GET', App\Controllers\CuotaController::class, 'show', true],
    'consultas' => ['GET', App\Controllers\ConsultaController::class, 'index', true],
    'consultas.create' => ['GET', App\Controllers\ConsultaController::class, 'create', true],
    'consultas.store' => ['POST', App\Controllers\ConsultaController::class, 'store', true],
    'consultas.edit' => ['GET', App\Controllers\ConsultaController::class, 'edit', true],
    'consultas.update' => ['POST', App\Controllers\ConsultaController::class, 'update', true],
    'consultas.destroy' => ['POST', App\Controllers\ConsultaController::class, 'destroy', true],
    'consultas.show' => ['GET', App\Controllers\ConsultaController::class, 'show', true],
    'consultas.pdf' => ['GET', App\Controllers\ConsultaController::class, 'pdf', true],
    'consultas.file' => ['GET', App\Controllers\ConsultaController::class, 'download', true],
    'vacunas' => ['GET', App\Controllers\VacunaController::class, 'index', true],
    'vacunas.create' => ['GET', App\Controllers\VacunaController::class, 'create', true],
    'vacunas.store' => ['POST', App\Controllers\VacunaController::class, 'store', true],
    'vacunas.edit' => ['GET', App\Controllers\VacunaController::class, 'edit', true],
    'vacunas.update' => ['POST', App\Controllers\VacunaController::class, 'update', true],
    'vacunas.destroy' => ['POST', App\Controllers\VacunaController::class, 'destroy', true],
    'vacunas.show' => ['GET', App\Controllers\VacunaController::class, 'show', true],
    'vencimientos' => ['GET', App\Controllers\VacunaController::class, 'history', true],
];
